---
- name: Ruby | Install Ruby
  apt: pkg=ruby update-cache=yes
  sudo: yes
  tags: ruby

- name: install rubygems
  apt: name=rubygems state=present
  sudo: yes
  tags: ruby

- name: Ruby | Install compass gem
  command: gem install compass
  sudo: yes
  tags: ruby